src/pattysPaintings/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace pattysPaintings.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        //public ActionResult Home()
        //{
        //    return View();
        //}
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/pattysPaintings/Controllers/pattyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace pattysPaintings.Controllers
{
    public class pattyController : Controller
    {
      
        public ActionResult Detail() //redirect and content result are inherited from ActionResult base class so can use for both returns below
        {
            ViewBag.PaintingTitle = "Spring Grand Lake"; //viewbag properties (not case sensitive
            ViewBag.Date = 2012;
            ViewBag.Location = "Grank Lake, CO";

            return View();


            //if (DateTime.Today.DayOfWeek == DayOfWeek.Tuesday) 
            //{
            //    return Redirect("/"); // if it's Tuesday then website is redirected to root of website (currently 404 error)
            //}
            //return Content("Hello from Patty Controller");
            
        }
        public ActionResult Detail2()
        {
            return View();
        }
        public ActionResult Outlined()
        {
            return View();
        }
        public ActionResult About()
        {
            return View();
        }
    }
}

src/pattysPaintings/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

    <div class="container">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="item active">
                    <img src="~/Images/alpine.jpg" alt="Alpine" style="width: auto; max-height: 500px; margin: auto;">
                </div>

                <div class="item">
                    <img src="~/Images/bearcub_gl.jpg" alt="Bear Cub" style="width: auto; max-height: 500px; margin: auto;">
                </div>

                <div class="item">
                    <img src="~/Images/DasBoot.jpg" alt="Das Boots" style="width: auto; max-height: 500px; margin: auto;">
                </div>
            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev"  max-width="300px">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next"  max-width="300px">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>

</body>
</html>

src/pattysPaintings/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Patricia Kiefer</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>



<body class="bg-light">
    <div class="container text-center">
        <h1 class="display-1">Patricia Kiefer</h1>
        <p class="lead">Paintings made by Patricia Kiefer and Website made by Jose</p>
        <ul class="nav justify-content-center">
            <li class="nav-item">
                <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>
            </li>
            <li class="nav-item">
                <li>@Html.ActionLink("Gallery", "Detail2", "patty", new { area = "" }, new { @class = "navbar-brand" })</li>
            </li>
            <li class="nav-item">
                <li>@Html.ActionLink("About", "About", "patty", new { area = "" }, new { @class = "navbar-brand" })</li>
            </li>
            <li class="nav-item">
                <li>@Html.ActionLink("Contact", "Detail", "patty", new { area = "" }, new { @class = "navbar-brand" })</li>
            </li>
        </ul>
        

    </div>
</body>



<div class="container body-content">
    @RenderBody() <!--render body method tells mvc where we want content from view-->
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - Kiefer Productons</p>
    </footer>
</div>
</html>

src/pattysPaintings/Views/patty/About.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>About Patricia Kiefer</h1>
<a href="~/Images/Oceanrock.jpg" target="_blank">
    <img src="~/Images/Oceanrock.jpg" class="rounded float-left" alt="Ocean Rock" />
</a>
    <blockquote class="blockquote text-right">
        <p class="mb-0">
            If a picture paints a thousand words then the words describing an oil painting are infinite. Painting in the oil medium is my craft, my passion, and some say my obsession. When I'm not painting I'm thinking about either my current project or maybe the next project as I desire the scent of mineral spirits, the smooth blending of oil colors on my palate, and the pleasant surprise of depth and dimension which accompanies light and shadow. Although I have fed my creative desires in many different ways I have studied and created oil paintings over the last 10 years. Simply stated… I love to paint and I find it necessary to paint daily to satisfy my creative moods.


        </p>
        <footer class="blockquote-footer">Warm Regards, <cite title="Source Title">Patricia Kiefer</cite></footer>
    </blockquote>

src/pattysPaintings/Views/patty/Detail.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Patty K Detail";
      
}
<div class="container left-align"    
    <div class="col-lg-6">
        <h1 class="display-5">Contact:</h1>
        <div class="input-group">
            <input type="text" class="form-control" placeholder="E-Mail Address" aria-label="E-Mail Address">
            <span class="input-group-btn">
                <button class="btn btn-primary" type="button">Submit</button>
            </span>
        </div>
    </div>
    <div class="col-lg-6">
        <label for="exampleFormControlTextarea1">Message:</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
    </div>
</div>
@*<h1>@ViewBag.paintingTitle</h1>
<h2>Date: @ViewBag.date</h2>

<h5>Location:</h5>
<div>@ViewBag.location</div>*@
    

src/pattysPaintings/Views/patty/Detail2.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{ 
    ViewBag.Title = "Index";
}
    <div class="container text-center">

        <h2>Image Gallery</h2>
        <p>The .thumbnail class can be used to display an image gallery.</p>
        <p>The .caption class adds proper padding and a dark grey color to text inside thumbnails.</p>
        <p>Click on the images to enlarge them.</p>

        <div class="row">
            <div class="col-md-4">
                <div class="thumbnail">
                    <a href="~/Images/ColoradoMorning.jpg" target="_blank">
                        <img src="~/Images/ColoradoMorning.jpg" class="img-circle" alt="Nature" style="width:100%">
                        <div class="caption">
                            <p>Nature Paintings</p>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="thumbnail">                  
                    <a href="~/Images/Abstracted_flower.jpg" target="_blank">
                        <img src="~/Images/Abstracted_flower.jpg" class="img-circle" alt="Abstract" style="width:100%">
                        <div class="caption">
                            <p>Abstract Paintings</p>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="thumbnail">
                    <a href="~/Images/Love,Mommy.jpg" target="_blank">
                        <img src="~/Images/Love,Mommy.jpg" class="img-circle" alt="Wild Life" style="width:100%">
                        <div class="caption">
                            <li>@Html.ActionLink("Outlined", "Outlined", "patty")</li>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>

src/pattysPaintings/Views/patty/Outlined.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Outlined";
}

<h2>Outlined Paintings</h2>

<img src="~/Images/buffsFlatIron.jpg" alt="Buffs Flatiron" />
<img src="~/Images/bearcub_gl.jpg" alt="Bear Cub" />
<img src="~/Images/night-sea.jpg" alt="Night Sea" />
<img src="~/Images/TuscanWindow.jpg" alt="Tuscan Window" />
<img src="~/Images/BearLake-Series3.jpg" alt="Bear Lake" />